apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-app
spec:
  selector:
    matchLabels:
      app: restaurant-app
  replicas: 2
  template:
    metadata:
      labels:
        app: restaurant-app
    spec:
      containers:
      - name: restaurant-app
        imagePullPolicy: Always
        image: quay.io/paurosello/challenge:latest
        env:
          - name: MONGO_URI
            value: mongodb://restaurant-mongo:27017/restaurant_app
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant-app
  labels:
    app: restaurant-app
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: restaurant-app
  type: LoadBalancer
